/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ReadingTestRouteImport } from './routes/reading-test'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TajweedIndexRouteImport } from './routes/tajweed.index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as TajweedRuleIdRouteImport } from './routes/tajweed.$ruleId'
import { Route as QuranSurahIdRouteImport } from './routes/quran.$surahId'
import { Route as TajweedGhunnahPracticeRouteImport } from './routes/tajweed.ghunnah.practice'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingTestRoute = ReadingTestRouteImport.update({
  id: '/reading-test',
  path: '/reading-test',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TajweedIndexRoute = TajweedIndexRouteImport.update({
  id: '/tajweed/',
  path: '/tajweed/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const TajweedRuleIdRoute = TajweedRuleIdRouteImport.update({
  id: '/tajweed/$ruleId',
  path: '/tajweed/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahIdRoute = QuranSurahIdRouteImport.update({
  id: '/$surahId',
  path: '/$surahId',
  getParentRoute: () => QuranRoute,
} as any)
const TajweedGhunnahPracticeRoute = TajweedGhunnahPracticeRouteImport.update({
  id: '/tajweed/ghunnah/practice',
  path: '/tajweed/ghunnah/practice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reading-test': typeof ReadingTestRoute
  '/signin': typeof SigninRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/tajweed/$ruleId': typeof TajweedRuleIdRoute
  '/quran/': typeof QuranIndexRoute
  '/tajweed/': typeof TajweedIndexRoute
  '/tajweed/ghunnah/practice': typeof TajweedGhunnahPracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reading-test': typeof ReadingTestRoute
  '/signin': typeof SigninRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/tajweed/$ruleId': typeof TajweedRuleIdRoute
  '/quran': typeof QuranIndexRoute
  '/tajweed': typeof TajweedIndexRoute
  '/tajweed/ghunnah/practice': typeof TajweedGhunnahPracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/reading-test': typeof ReadingTestRoute
  '/signin': typeof SigninRoute
  '/quran/$surahId': typeof QuranSurahIdRoute
  '/tajweed/$ruleId': typeof TajweedRuleIdRoute
  '/quran/': typeof QuranIndexRoute
  '/tajweed/': typeof TajweedIndexRoute
  '/tajweed/ghunnah/practice': typeof TajweedGhunnahPracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboarding'
    | '/reading-test'
    | '/signin'
    | '/quran/$surahId'
    | '/tajweed/$ruleId'
    | '/quran/'
    | '/tajweed/'
    | '/tajweed/ghunnah/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/reading-test'
    | '/signin'
    | '/quran/$surahId'
    | '/tajweed/$ruleId'
    | '/quran'
    | '/tajweed'
    | '/tajweed/ghunnah/practice'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboarding'
    | '/reading-test'
    | '/signin'
    | '/quran/$surahId'
    | '/tajweed/$ruleId'
    | '/quran/'
    | '/tajweed/'
    | '/tajweed/ghunnah/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ReadingTestRoute: typeof ReadingTestRoute
  SigninRoute: typeof SigninRoute
  TajweedRuleIdRoute: typeof TajweedRuleIdRoute
  QuranIndexRoute: typeof QuranIndexRoute
  TajweedIndexRoute: typeof TajweedIndexRoute
  TajweedGhunnahPracticeRoute: typeof TajweedGhunnahPracticeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-test': {
      id: '/reading-test'
      path: '/reading-test'
      fullPath: '/reading-test'
      preLoaderRoute: typeof ReadingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tajweed/': {
      id: '/tajweed/'
      path: '/tajweed'
      fullPath: '/tajweed/'
      preLoaderRoute: typeof TajweedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tajweed/$ruleId': {
      id: '/tajweed/$ruleId'
      path: '/tajweed/$ruleId'
      fullPath: '/tajweed/$ruleId'
      preLoaderRoute: typeof TajweedRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surahId': {
      id: '/quran/$surahId'
      path: '/$surahId'
      fullPath: '/quran/$surahId'
      preLoaderRoute: typeof QuranSurahIdRouteImport
      parentRoute: typeof QuranRoute
    }
    '/tajweed/ghunnah/practice': {
      id: '/tajweed/ghunnah/practice'
      path: '/tajweed/ghunnah/practice'
      fullPath: '/tajweed/ghunnah/practice'
      preLoaderRoute: typeof TajweedGhunnahPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ReadingTestRoute: ReadingTestRoute,
  SigninRoute: SigninRoute,
  TajweedRuleIdRoute: TajweedRuleIdRoute,
  QuranIndexRoute: QuranIndexRoute,
  TajweedIndexRoute: TajweedIndexRoute,
  TajweedGhunnahPracticeRoute: TajweedGhunnahPracticeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
